export const vendorsListings = [
  {
    id: 1,
    name: "Pakaard Media",
    image: "/images/Pakaard.png",
    description:
      "A media outfit specialized in delivering beautiful top-notch images at very affordable rates for all events.",
    job: "photography video photo videography",
    location: "Abuja, Nigeria.",
    fullname: "Iyanuoluwa",
    phone: "08100308391",
    social: "IG: pakaard",
    service: "Photographer",
    experience: "2 years",
    rating: 4.5,
  },
  {
    id: 2,
    name: "Moncherri Confectionery",
    image: "/images/Moncherri_Confectionery.png",
    description:
      "Mon Cherri Confectionery is a brand that gives delicious cakes and pastries that are perfect for any occasion.",
    job: "catering chef cake",
    location: "Lagos, Nigeria",
    fullname: "Okeya Ayotomiwa",
    phone: "08036815819",
    social: "Moncherri_Confectionery",
    service: "Baker",
    experience: "2 years",
    rating: 4.5,
  },
  {
    id: 3,
    name: "Cherry Gold Confectionery",
    image: "/images/Cherry.png",
    description:
      "Cherry Gold Confectionery offers customers yummy, beautiful, mouth-watering birthday cake, small chops, and pastries with a touch of love.",
    job: "catering cake pastries small chops",
    location: "Abuja, Nigeria",
    fullname: "Adewale Sherifat",
    phone: "08105050078",
    social: " IG @cherry_gold.confectionery",
    service: "Baker",
    experience: "3 years",
    rating: 4.2,
  },
  {
    id: 4,
    name: "Mercuria Business Network",
    image: "/images/mercuria.png",
    description: "We are into delivering services for events and catering.",
    job: "event planner business catering",
    location: "Akwa Ibom, Nigeria.",
    fullname: "Nkese Eyo",
    phone: "07039584426",
    social: "@Mercuriachops@Memo",
    service: "Event Decorator",
    experience: "12 years",
    rating: 4.9,
  },
  {
    id: 5,
    name: "Wildcard prints",
    image: "/images/wildcard.png",
    description:
      "Wildcard prints is a company that gives bespoke printing services for all events and gatherings. We are your go to for achieving high quality design and branding for your events.",
    job: "printing design branding invitation iv card banner souvenirs",
    location: "Lagos, Nigeria.",
    fullname: "Anthony",
    phone: "09125265710",
    social: "Thread: @wildcard_prints, IG: wildcard_prints",
    service: "Printer",
    experience: "7 years",
    rating: 4.7,
  },
  {
    id: 6,
    name: "Chef nahnah Foods",
    image: "/images/nahnah.png",
    description:
      "Chef Nahnah foods and confectionary ltd is a modern and exquisite pastry company that produces food and treats cutting across all classes.",
    job: "chef food cook",
    location: "Lagos, Nigeria.",
    fullname: "Nancy Amaku",
    phone: "+2348188002579",
    social: "@chef.nahnah",
    service: "Small chops vendor",
    experience: "3 years",
    rating: 4.8,
  },
  {
    id: 7,
    name: "Jenny's Glam",
    image: "/images/jenny.png",
    description: "Make up.",
    job: "makeup",
    location: "Lagos, Nigeria.",
    fullname: "Jennifer Alechenu",
    phone: "09021419373",
    social: "Jennys_glamm",
    service: "Beautician",
    experience: "8 years",
    rating: 4.5,
  },
  {
    id: 8,
    name: "Bee's smoothies and juice",
    image: "/images/bee.png",
    description:
      "One-stop shop for all your healthy yet, delicious fresh smoothies and juices.",
    job: "smoothie juice fruit",
    location: "Abuja, Nigeria.",
    fullname: "Brenda Terry",
    phone: "07061013553",
    social: "Beessmoothiesandjuice",
    service: "Fresh fruits juice/smoothies",
    experience: "4 years",
    rating: 4.2,
  },
  {
    id: 9,
    name: "Real Leather",
    image: "/images/real.png",
    description: "Into Manufacturing of shoes.",
    job: "cobbler shoe shoemaker leather",
    location: "FUTA AKURE.",
    fullname: "Dare Samson",
    phone: "+2348163319574",
    social: "https://m.facebook.com/realleather",
    service: "Leatherworks",
    experience: "5 years",
    rating: 4.5,
  },
  {
    id: 10,
    name: "Soo Casual",
    image: "/images/soo.png",
    description: "Designing.",
    job: "fashion design fashiondesign",
    location: "Abuja, Nigeria.",
    fullname: "Soo Jasmine",
    phone: "07035384483",
    social: "Soo__casual",
    service: "Fashion Designer",
    experience: "4 years",
    rating: 4.9,
  },
  {
    id: 11,
    name: "Mariposa Fruits Co",
    image: "/images/mariposa.png",
    description:
      "We sell parfaits, smoothies and juices, fruit trees and chocolate fountains, cocktails and mocktails, salads and sandwiches.",
    job: "juice fruit smoothie parfait chocolate fountains cocktails mocktails salads sandwiches",
    location: "Lagos, Nigeria.",
    fullname: "Detola Adebiyi",
    phone: "08062712107",
    social: "@mariposa_fruits",
    service: "Catering",
    experience: "5 years",
    rating: 4.6,
  },
  {
    id: 12,
    name: "His Touch Studios",
    image: "/images/touch.png",
    description:
      "His Touch Studios is a professional event Photography company with an experience of over a decade. We are known for quality service and prompt delivery.",
    job: "photographer photo video videographer",
    location: "Ibadan, Nigeria.",
    fullname: "Tolulope Adedayo Odusina",
    phone: "08109219897",
    social: "@histouchstudios",
    service: "Photographer",
    experience: "13 years",
    rating: 4.9,
  },
  {
    id: 13,
    name: "Surshi's cuisine",
    image: "/images/surshi.png",
    description: "Food, snacks, beverages, soup bowls.",
    job: "food cuisine snacks beverages soup bowls",
    location: "Abuja, Nigeria.",
    fullname: "Surshima",
    phone: "07039198856",
    social: "Surshi's cuisine (Instagram) surshi's cuisine (Facebook)",
    service: "Catering",
    experience: "4 years",
    rating: 4.7,
  },
  {
    id: 14,
    name: "Imv hub",
    image: "/images/imv.png",
    description: "Marketing and technology agency.",
    job: "marketer marketing promote promoter",
    location: "Lagos, Nigeria.",
    fullname: "Olumide Adeyanju",
    phone: "+2348123230461",
    social: "@imvhub",
    service: "Media",
    experience: "3 years",
    rating: 4.2,
  },
  {
    id: 15,
    name: "Maybeth Decors & Events",
    image: "/images/maybeth.png",
    description:
      "Maybeth Decors & Event is an event Decoration company based in Lagos that caters for both social & corporate Events. We also have the rental arm of the company.",
    job: "event planner eventplanner decoration",
    location: "Lagos, Nigeria.",
    fullname: "Elizabeth Owoseni",
    phone: "08082709988",
    social: "www.instagram.com/maybetheventsng",
    service: "Decoration",
    experience: "10 years",
    rating: 4.5,
  },
  {
    id: 16,
    name: "Veroni_hairs",
    image: "/images/veroni.png",
    description: "We deal in all kinds of human hair and accessories.",
    job: "hairstylist hair vendor",
    location: "Mabushi, Abuja.",
    fullname: "Jennifer ogwude",
    phone: "09163181254",
    social: "veroni_hairs",
    service: "Makeup Artist",
    experience: "3 years",
    rating: 4.3,
  },
];